### ISSUE TITLE
Code review for Tweet Generator Submission 1

### ISSUE THREAD

**Issue by SWHarrison** [Jeromeschmidt/CS-1.2-Intro-Data-Structures#1]
1. dictionary_words works well and is optimized for run time. Try adding benchmarking to see if there are alternative ways to choose random words. One possibility is to randomly select words as you are reading in to avoid going through the list an additional time.
2. Great work on the different types of histograms. I noticed the listogram tests took a while to run. I would encourage you to look and see if there are any unoptimized pieces of code slowing down the test. I am not noticing anything currently, but I might have missed something.
3. Sampling works as expected.
4. Heroku app is working and looks nice, great job!
5. Cannot get markov chain script to work, even after uncommenting the constructor.

**Comment by Jeromeschmidt** [comment]
Thanks for the great feedback. There was an issue with the Markov chain on the website but it is fixed now. I'll take a look at the listogram and see whats causing that!
