### ISSUE TITLE
Linked List feedback

### ISSUE THREAD

**Issue by lvreynoso** [Jeromeschmidt/CS-1.2-Intro-Data-Structures#2]
Hi Jerome! I've graded your linked list submission and have some feedback for you:

- good job passing all unit tests
- I did not see any additional unit tests written.
- your `find()` method has an unused variable, `test_node = Node(quality)`, not sure what was going on here but it's always good practice to eliminate dangling statements
- could use more comments in your code
- missing explanations for your time complexity analysis
- your `delete()` method actually has worst case time complexity of `O(n)` since, in order to delete the last node, your code will have to traverse the whole list
- `delete()` method also does not account for `prev` connections in a doubly-linked list
- I think you were trying to make your linked list iterable with your `iterate()` method, but that's not quite what the challenge is - see [this article about `__iter__()`](https://www.programiz.com/python-programming/iterator)

**Comment by Jeromeschmidt** [comment]
Thanks for the awesome feedback Lucia! I fixed the issues that were mentioned in my code above and added or changed the respective unit tests to reflect a doubly linked list.
